project:
  type: website
  output-dir: docs

website:
  title: "Noelle Broughton"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research

format:
  html:
    theme: flatly
    toc: false